- name: Installs prereqs
  apt: >
    pkg=git
    state=latest

- name: Creates deploy user
  user: >
    name={{ dummy_php_app_user }}
    comment="Web application user"
    shell=/bin/bash

- name: Creates deploy directory
  file: >
    path={{ dummy_php_app_deploy_dir }}
    owner={{ dummy_php_app_user }}
    state=directory

- name: Checkout app
  sudo_user: "{{ dummy_php_app_user }}"
  sudo: true
  git: >
    repo={{ dummy_php_app_repos }}
    dest={{ dummy_php_app_deploy_dir }}/dummy-php-app/
    accept_hostkey=true
    force=yes
  register: dummy_php_app_deployed

- name: Adds config to nginx
  template: >
    src="../templates/dummy-php-app.conf.j2"
    dest=/etc/nginx/sites-available/dummy-php-app.conf
    backup=yes

- name: Symlinks config
  file: >
    src=/etc/nginx/sites-available/dummy-php-app.conf
    dest=/etc/nginx/sites-enabled/dummy-php-app.conf
    state=link
  notify: Restart nginx

- name: Removes default config
  file: >
    path=/etc/nginx/sites-{{ item }}/default
    state=absent
  with_items:
    - available
    - enabled
  notify: Restart nginx

- name: set port to check
  set_fact: check_port={{ dummy_php_app_port }}
